### ISSUE TITLE
release version 0.3.0

### ISSUE THREAD

**Issue by schengawegga** [pear/Auth_SASL2#6]
prepare and release version 0.3.0

**Comment by Neustradamus** [comment]
@schengawegga, @CloCkWeRX: Can you merge all from https://github.com/pear/Auth_SASL2/tree/v0.3.0 into master and remove v0.3.0 branch?

Can you do this issue too?
- https://github.com/pear/Auth_SASL2/issues/9

Can you create the build too?

**Comment by schengawegga** [comment]
@Neustradamus i will do an v0.2.1 build these days with the srcamsha224 bugfix.

**Comment by Neustradamus** [comment]
@schengawegga: Why not better to release the 0.3.0 with deprecated too?

**Comment by schengawegga** [comment]
@Neustradamus we will see. my time is very limited at the moment. so we will see what i can do in the next release.

**Comment by Neustradamus** [comment]
@schengawegga: Can you look to do before 2023 ending?

**Comment by schengawegga** [comment]
version 0.3.0 released

**Comment by Neustradamus** [comment]
@schengawegga: Good job!
- https://github.com/pear/Auth_SASL2/releases/tag/v0.3.0
