### ISSUE TITLE
mark authentication methods cram-md5, digest-md5, and login as deprecated

### ISSUE THREAD

**Issue by schengawegga** [pear/Auth_SASL2#9]
mark authentication methods cram-md5, digest-md5, plain, login and anonymous as deprecated

**Comment by Neustradamus** [comment]
@schengawegga: PLAIN must not be noted "DEPRECATED".

**Comment by Neustradamus** [comment]
@schengawegga, @CloCkWeRX: Can you do it before the 0.3.0 build?

It is needed for https://github.com/pear/Net_SMTP.

**Comment by schengawegga** [comment]
@Neustradamus i will do that with the 0.2.1 build, these days.

**Comment by Neustradamus** [comment]
Same than Auth_SASL, "mark authentication methods cram-md5, digest-md5, and login as deprecated"

**Comment by Neustradamus** [comment]
@schengawegga: Good job!
- https://github.com/pear/Auth_SASL2/issues/6
- https://github.com/pear/Auth_SASL2/pull/11
- https://github.com/pear/Auth_SASL2/releases/tag/v0.3.0

You can add the hashtag 9 too in 0.3.0 description :)
